local ped_models={}
ped_models.ver_text = "Gee-Skid v2.07"
local get_hash = gameplay.get_hash_key

ped_models.types={
--{"a_c","Animal Character"},
{"a_f_m","Actor/Ambient Female Middleage"},
{"a_f_o","Actor/Ambient Female Old"},
{"a_f_y","Actor/Ambient Female Young"},
{"a_m_m","Actor/Ambient Male Middleage"},
{"a_m_o","Actor/Ambient Male Old"},
{"a_m_y","Actor/Ambient Male Young"},
{"g_f_y","Gang Female Young"},
{"g_m_m","Gang Male Middleage"},
{"g_m_y","Gang Male Young"},
{"hc","Heist Character/Crew"},
{"ig","Game Character"},
{"mp_f","Multiplayer Female"},
{"mp_m","Multiplayer Male"},
{"player_","Story Mode Character"},
{"s_f_m","Service Female Middleage"},
{"s_f_y","Service Female Young"},
{"s_m_m","Service Male Middleage"},
{"s_m_y","Service Male Young"},
{"u_f_m","Unique Female Middleage"},
{"u_f_o","Unique Female Old"},
{"u_f_y","Unique Female Young"},
{"u_m_m","Unique Male Middleage"},
{"u_m_o","Unique Male Old"},
{"u_m_y","Unique Male Young"},
}

ped_models.peds={
{"a_f_m_beach_01","Beach Female"},
{"a_f_m_bevhills_01","Beverly Hills Female"},
{"a_f_m_bevhills_02","Beverly Hills Female 2"},
{"a_f_m_bodybuild_01","Bodybuilder Female"},
{"a_f_m_business_02","Business Female 2"},
{"a_f_m_downtown_01","Downtown Female"},
{"a_f_m_eastsa_01","East SA Female"},
{"a_f_m_eastsa_02","East SA Female 2"},
{"a_f_m_fatbla_01","Fat Black Female"},
{"a_f_m_fatcult_01","Fat Cult Female"},
{"a_f_m_fatwhite_01","Fat White Female"},
{"a_f_m_ktown_01","Korean Female"},
{"a_f_m_ktown_02","Korean Female 2"},
{"a_f_m_prolhost_01","Prologue Host Female"},
{"a_f_m_salton_01","Salton Female"},
{"a_f_m_skidrow_01","Skid Row Female"},
{"a_f_m_soucent_01","South Central Female"},
{"a_f_m_soucent_02","South Central Female 2"},
{"a_f_m_soucentmc_01","South Central MC Female"},
{"a_f_m_tourist_01","Tourist Female"},
{"a_f_m_tramp_01","Tramp Female"},
{"a_f_m_trampbeac_01","Beach Tramp Female"},
{"a_f_o_genstreet_01","General Street Old Female"},
{"a_f_o_indian_01","Indian Old Female"},
{"a_f_o_ktown_01","Korean Old Female"},
{"a_f_o_salton_01","Salton Old Female"},
{"a_f_o_soucent_01","South Central Old Female"},
{"a_f_o_soucent_02","South Central Old Female 2"},
{"a_f_y_beach_01","Beach Young Female"},
{"a_f_y_bevhills_01","Beverly Hills Young Female"},
{"a_f_y_bevhills_02","Beverly Hills Young Female 2"},
{"a_f_y_bevhills_03","Beverly Hills Young Female 3"},
{"a_f_y_bevhills_04","Beverly Hills Young Female 4"},
{"a_f_y_business_01","Business Young Female"},
{"a_f_y_business_02","Business Young Female 2"},
{"a_f_y_business_03","Business Young Female 3"},
{"a_f_y_business_04","Business Young Female 4"},
{"a_f_y_clubcust_01","Clubcust 1"},
{"a_f_y_clubcust_02","Clubcust 2"},
{"a_f_y_clubcust_03","Clubcust 3"},
{"a_f_y_eastsa_01","East SA Young Female"},
{"a_f_y_eastsa_02","East SA Young Female 2"},
{"a_f_y_eastsa_03","East SA Young Female 3"},
{"a_f_y_epsilon_01","Epsilon Female"},
{"a_f_y_femaleagent","Female Agent"},
{"a_f_y_fitness_01","Fitness Female"},
{"a_f_y_fitness_02","Fitness Female 2"},
{"a_f_y_genhot_01","General Hot Young Female"},
{"a_f_y_golfer_01","Golfer Young Female"},
{"a_f_y_hiker_01","Hiker Female"},
{"a_f_y_hippie_01","Hippie Female"},
{"a_f_y_hipster_01","Hipster Female"},
{"a_f_y_hipster_02","Hipster Female 2"},
{"a_f_y_hipster_03","Hipster Female 3"},
{"a_f_y_hipster_04","Hipster Female 4"},
{"a_f_y_indian_01","Indian Young Female"},
{"a_f_y_juggalo_01","Juggalo Female"},
{"a_f_y_runner_01","Jogger Female"},
{"a_f_y_rurmeth_01","Rural Meth Addict Female"},
{"a_f_y_scdressy_01","Dressy Female"},
{"a_f_y_skater_01","Skater Female"},
{"a_f_y_soucent_01","South Central Young Female"},
{"a_f_y_soucent_02","South Central Young Female 2"},
{"a_f_y_soucent_03","South Central Young Female 3"},
{"a_f_y_tennis_01","Tennis Player Female"},
{"a_f_y_topless_01","Topless"},
{"a_f_y_tourist_01","Tourist Young Female"},
{"a_f_y_tourist_02","Tourist Young Female 2"},
{"a_f_y_vinewood_01","Vinewood Female"},
{"a_f_y_vinewood_02","Vinewood Female 2"},
{"a_f_y_vinewood_03","Vinewood Female 3"},
{"a_f_y_vinewood_04","Vinewood Female 4"},
{"a_f_y_yoga_01","Yoga Female"},
{"a_m_m_acult_01","Altruist Cult Mid-Age Male"},
{"a_m_m_afriamer_01","African American Male"},
{"a_m_m_beach_01","Beach Male"},
{"a_m_m_beach_02","Beach Male 2"},
{"a_m_m_bevhills_01","Beverly Hills Male"},
{"a_m_m_bevhills_02","Beverly Hills Male 2"},
{"a_m_m_business_01","Business Male"},
{"a_m_m_eastsa_01","East SA Male"},
{"a_m_m_eastsa_02","East SA Male 2"},
{"a_m_m_farmer_01","Farmer"},
{"a_m_m_fatlatin_01","Fat Latino Male"},
{"a_m_m_genfat_01","General Fat Male"},
{"a_m_m_genfat_02","General Fat Male 2"},
{"a_m_m_golfer_01","Golfer Male"},
{"a_m_m_hasjew_01","Hasidic Jew Male"},
{"a_m_m_hillbilly_01","Hillbilly Male"},
{"a_m_m_hillbilly_02","Hillbilly Male 2"},
{"a_m_m_indian_01","Indian Male"},
{"a_m_m_ktown_01","Korean Male"},
{"a_m_m_malibu_01","Malibu Male"},
{"a_m_m_mexcntry_01","Mexican Rural"},
{"a_m_m_mexlabor_01","Mexican Labourer"},
{"a_m_m_og_boss_01","OG Boss"},
{"a_m_m_paparazzi_01","Paparazzi Male"},
{"a_m_m_polynesian_01","Polynesian"},
{"a_m_m_prolhost_01","Prologue Host Male"},
{"a_m_m_rurmeth_01","Rural Meth Addict Male"},
{"a_m_m_salton_01","Salton Male"},
{"a_m_m_salton_02","Salton Male 2"},
{"a_m_m_salton_03","Salton Male 3"},
{"a_m_m_salton_04","Salton Male 4"},
{"a_m_m_skater_01","Skater Male"},
{"a_m_m_skidrow_01","Skid Row Male"},
{"a_m_m_socenlat_01","South Central Latino Male"},
{"a_m_m_soucent_01","South Central Male"},
{"a_m_m_soucent_02","South Central Male 2"},
{"a_m_m_soucent_03","South Central Male 3"},
{"a_m_m_soucent_04","South Central Male 4"},
{"a_m_m_stlat_02","Latino Street Male 2"},
{"a_m_m_tennis_01","Tennis Player Male"},
{"a_m_m_tourist_01","Tourist Male"},
{"a_m_m_tramp_01","Tramp Male"},
{"a_m_m_trampbeac_01","Beach Tramp Male"},
{"a_m_m_tranvest_01","Transvestite Male"},
{"a_m_m_tranvest_02","Transvestite Male 2"},
{"a_m_o_acult_01","Altruist Cult Old Male"},
{"a_m_o_acult_02","Altruist Cult Old Male 2"},
{"a_m_o_beach_01","Beach Old Male"},
{"a_m_o_genstreet_01","General Street Old Male"},
{"a_m_o_ktown_01","Korean Old Male"},
{"a_m_o_salton_01","Salton Old Male"},
{"a_m_o_soucent_01","South Central Old Male"},
{"a_m_o_soucent_02","South Central Old Male 2"},
{"a_m_o_soucent_03","South Central Old Male 3"},
{"a_m_o_tramp_01","Tramp Old Male"},
{"a_m_y_acult_01","Altruist Cult Young Male"},
{"a_m_y_acult_02","Altruist Cult Young Male 2"},
{"a_m_y_beach_01","Beach Young Male"},
{"a_m_y_beach_02","Beach Young Male 2"},
{"a_m_y_beach_03","Beach Young Male 3"},
{"a_m_y_beachvesp_01","Vespucci Beach Male"},
{"a_m_y_beachvesp_02","Vespucci Beach Male 2"},
{"a_m_y_bevhills_01","Beverly Hills Young Male"},
{"a_m_y_bevhills_02","Beverly Hills Young Male 2"},
{"a_m_y_breakdance_01","Breakdancer Male"},
{"a_m_y_busicas_01","Business Casual"},
{"a_m_y_business_01","Business Young Male"},
{"a_m_y_business_02","Business Young Male 2"},
{"a_m_y_business_03","Business Young Male 3"},
{"a_m_y_clubcust_01","Club Cust 1"},
{"a_m_y_clubcust_02","Club Cust 2"},
{"a_m_y_clubcust_03","Club Cust 3"},
{"a_m_y_cyclist_01","Cyclist Male"},
{"a_m_y_dhill_01","Downhill Cyclist"},
{"a_m_y_downtown_01","Downtown Male"},
{"a_m_y_eastsa_01","East SA Young Male"},
{"a_m_y_eastsa_02","East SA Young Male 2"},
{"a_m_y_epsilon_01","Epsilon Male"},
{"a_m_y_epsilon_02","Epsilon Male 2"},
{"a_m_y_gay_01","Gay Male"},
{"a_m_y_gay_02","Gay Male 2"},
{"a_m_y_genstreet_01","General Street Young Male"},
{"a_m_y_genstreet_02","General Street Young Male 2"},
{"a_m_y_golfer_01","Golfer Young Male"},
{"a_m_y_hasjew_01","Hasidic Jew Young Male"},
{"a_m_y_hiker_01","Hiker Male"},
{"a_m_y_hippy_01","Hippie Male"},
{"a_m_y_hipster_01","Hipster Male"},
{"a_m_y_hipster_02","Hipster Male 2"},
{"a_m_y_hipster_03","Hipster Male 3"},
{"a_m_y_indian_01","Indian Young Male"},
{"a_m_y_jetski_01","Jetskier"},
{"a_m_y_juggalo_01","Juggalo Male"},
{"a_m_y_ktown_01","Korean Young Male"},
{"a_m_y_ktown_02","Korean Young Male 2"},
{"a_m_y_latino_01","Latino Young Male"},
{"a_m_y_methhead_01","Meth Addict"},
{"a_m_y_mexthug_01","Mexican Thug"},
{"a_m_y_motox_01","Motocross Biker"},
{"a_m_y_motox_02","Motocross Biker 2"},
{"a_m_y_musclbeac_01","Beach Muscle Male"},
{"a_m_y_musclbeac_02","Beach Muscle Male 2"},
{"a_m_y_polynesian_01","Polynesian Young"},
{"a_m_y_roadcyc_01","Road Cyclist"},
{"a_m_y_runner_01","Jogger Male"},
{"a_m_y_runner_02","Jogger Male 2"},
{"a_m_y_salton_01","Salton Young Male"},
{"a_m_y_skater_01","Skater Young Male"},
{"a_m_y_skater_02","Skater Young Male 2"},
{"a_m_y_soucent_01","South Central Young Male"},
{"a_m_y_soucent_02","South Central Young Male 2"},
{"a_m_y_soucent_03","South Central Young Male 3"},
{"a_m_y_soucent_04","South Central Young Male 4"},
{"a_m_y_stbla_01","Black Street Male"},
{"a_m_y_stbla_02","Black Street Male 2"},
{"a_m_y_stlat_01","Latino Street Young Male"},
{"a_m_y_stwhi_01","White Street Male"},
{"a_m_y_stwhi_02","White Street Male 2"},
{"a_m_y_sunbathe_01","Sunbather Male"},
{"a_m_y_surfer_01","Surfer"},
{"a_m_y_vindouche_01","Vinewood Douche"},
{"a_m_y_vinewood_01","Vinewood Male"},
{"a_m_y_vinewood_02","Vinewood Male 2"},
{"a_m_y_vinewood_03","Vinewood Male 3"},
{"a_m_y_vinewood_04","Vinewood Male 4"},
{"a_m_y_yoga_01","Yoga Male"},
{"cs_amandatownley","Amanda De Santa"},
{"cs_andreas","Andreas Sanchez"},
{"cs_ashley","Ashley Butler"},
{"cs_bankman","Bank Manager"},
{"cs_barry","Barry"},
{"cs_barry_p","Barry"},
{"cs_beverly","Beverly Felton"},
{"cs_beverly_p","Beverly Felton"},
{"cs_brad","Brad"},
{"cs_bradcadaver","Brad's Cadaver"},
{"cs_carbuyer","Car Buyer"},
{"cs_casey","Casey"},
{"cs_chengsr","Wei Cheng"},
{"cs_chrisformage","Cris Formage"},
{"cs_clay","Clay Simons (The Lost)"},
{"cs_dale","Dale"},
{"cs_davenorton","Dave Norton"},
{"cs_debra","Debra"},
{"cs_denise","Denise"},
{"cs_devin","Devin"},
{"cs_dom","Dom Beasley"},
{"cs_dreyfuss","Peter Dreyfuss"},
{"cs_drfriedlander","Dr. Friedlander"},
{"cs_fabien","Fabien"},
{"cs_fbisuit_01","FIB Suit"},
{"cs_floyd","Floyd Hebert"},
{"cs_guadalope","Guadalope"},
{"cs_gurk","GURK?"},
{"cs_hunter","Hunter"},
{"cs_janet","Janet"},
{"cs_jewelass","Jeweller Assistant"},
{"cs_jimmyboston","Jimmy Boston"},
{"cs_jimmydisanto","Jimmy De Santa"},
{"cs_joeminuteman","Minuteman Joe"},
{"cs_johnnyklebitz","Johnny Klebitz"},
{"cs_josef","Josef"},
{"cs_josh","Josh"},
{"cs_karen_daniels","Karen Daniels"},
{"cs_lamardavis","Lamar Davis"},
{"cs_lazlow","Lazlow"},
{"cs_lestercrest","Lester Crest"},
{"cs_lifeinvad_01","Life Invader"},
{"cs_magenta","Magenta"},
{"cs_manuel","Manuel"},
{"cs_marnie","Marnie Allen"},
{"cs_martinmadrazo","Martin Madrazo"},
{"cs_maryann","Mary-Ann Quinn"},
{"cs_michelle","Michelle"},
{"cs_milton","Milton McIlroy"},
{"cs_molly","Molly"},
{"cs_movpremf_01","Movie Premiere Female"},
{"cs_movpremmale","Movie Premiere Male"},
{"cs_mrk","Ferdinand Kerimov (Mr. K)"},
{"cs_mrs_thornhill","Mrs. Thornhill"},
{"cs_mrsphillips","Mrs. Phillips"},
{"cs_natalia","Natalia"},
{"cs_nervousron","Nervous Ron"},
{"cs_nigel","Nigel"},
{"cs_old_man1a","Old Man 1"},
{"cs_old_man2","Old Man 2"},
{"cs_omega","Omega"},
{"cs_orleans","Bigfoot"},
{"cs_paper","United Paper Man"},
{"cs_paper_p","United Paper Man"},
{"cs_patricia","Patricia"},
{"cs_priest","Priest"},
{"cs_prolsec_02","Prologue Security 2"},
{"cs_russiandrunk","Russian Drunk"},
{"cs_siemonyetarian","Simeon Yetarian"},
{"cs_solomon","Solomon Richards"},
{"cs_stevehains","Steve Haines"},
{"cs_stretch","Stretch"},
{"cs_tanisha","Tanisha"},
{"cs_taocheng","Tao Cheng"},
{"cs_taostranslator","Tao's Translator"},
{"cs_tenniscoach","Tennis Coach"},
{"cs_terry","Terry"},
{"cs_tom","Tom"},
{"cs_tomepsilon","Epsilon Tom"},
{"cs_tracydisanto","Tracey De Santa"},
{"cs_wade","Wade"},
{"cs_zimbor","Zimbor"},
{"csb_abigail","Abigail Mathers"},
{"csb_agent","Agent"},
{"csb_anita","Anita Mendoza"},
{"csb_anton","Anton Beaudelaire"},
{"csb_avon","Avon Hertz"},
{"csb_ballasog","Ballas OG"},
{"csb_bogdan","Bogdan"},
{"csb_bride","Bride"},
{"csb_burgerdrug","Burger Drug Worker"},
{"csb_car3guy1","Car 3 Guy 1"},
{"csb_car3guy2","Car 3 Guy 2"},
{"csb_chef2","Chef"},
{"csb_chef","Chef"},
{"csb_chin_goon","Chinese Goon"},
{"csb_cletus","Cletus"},
{"csb_cop","Cop"},
{"csb_customer","Customer"},
{"csb_denise_friend","Denise's Friend"},
{"csb_dix","Dix"},
{"csb_djblamadon","DJ Blamadon"},
{"csb_englishdave","English Dave"},
{"csb_fos_rep","FOS Rep?"},
{"csb_g","Gerald"},
{"csb_groom","Groom"},
{"csb_grove_str_dlr","Grove Street Dealer"},
{"csb_hao","Hao"},
{"csb_hugh","Hugh Welsh"},
{"csb_imran","Imran Shinowa"},
{"csb_jackhowitzer","Jack Howitzer"},
{"csb_janitor","Janitor"},
{"csb_maude","Maude"},
{"csb_money","Money Man"},
{"csb_mp_agent14","Agent 14"},
{"csb_mrs_r","Mrs. Rackman"},
{"csb_mweather","Merryweather Merc"},
{"csb_ortega","Ortega"},
{"csb_oscar","Oscar"},
{"csb_paige","Paige Harris"},
{"csb_popov","Dima Popov"},
{"csb_porndudes","Porn Dude"},
{"csb_porndudes_p","Porn Dude"},
{"csb_prologuedriver","Prologue Driver"},
{"csb_prolsec","Prologue Security"},
{"csb_ramp_gang","Families Gang Member?"},
{"csb_ramp_hic","Hick"},
{"csb_ramp_hipster","Hipster"},
{"csb_ramp_marine","Marine"},
{"csb_ramp_mex","Mexican"},
{"csb_rashcosvki","Maxim Rashkovsky"},
{"csb_reporter","Reporter"},
{"csb_roccopelosi","Rocco Pelosi"},
{"csb_screen_writer","Screenwriter"},
{"csb_sol","Sol"},
{"csb_stripper_01","Stripper"},
{"csb_stripper_02","Stripper 2"},
{"csb_talcc","Talc C"},
{"csb_talmm","Talm M"},
{"csb_tonya","Tonya"},
{"csb_tonyprince","Tony Prince"},
{"csb_trafficwarden","Traffic Warden"},
{"csb_undercover","Undercover Cop"},
{"csb_vagspeak","Vagos Speak"},
{"g_f_importexport_01","Gang Female (Import-Export)"},
{"g_f_y_ballas_01","Ballas Female"},
{"g_f_y_families_01","Families Female"},
{"g_f_y_lost_01","The Lost MC Female"},
{"g_f_y_vagos_01","Vagos Female"},
{"g_m_importexport_01","Gang Male (Import-Export)"},
{"g_m_m_armboss_01","Armenian Boss"},
{"g_m_m_armgoon_01","Armenian Goon"},
{"g_m_m_armlieut_01","Armenian Lieutenant"},
{"g_m_m_chemwork_01_p","Chemical Plant Worker"},
{"g_m_m_chemwork_01","Chemical Plant Worker"},
{"g_m_m_chiboss_01","Chinese Boss"},
{"g_m_m_chiboss_01_p","Chinese Boss"},
{"g_m_m_chicold_01","Chinese Goon Older"},
{"g_m_m_chicold_01_p","Chinese Goon Older"},
{"g_m_m_chigoon_01","Chinese Goon"},
{"g_m_m_chigoon_01_p","Chinese Goon"},
{"g_m_m_chigoon_02","Chinese Goon 2"},
{"g_m_m_korboss_01","Korean Boss"},
{"g_m_m_mexboss_01","Mexican Boss"},
{"g_m_m_mexboss_02","Mexican Boss 2"},
{"g_m_y_armgoon_02","Armenian Goon 2"},
{"g_m_y_azteca_01","Azteca"},
{"g_m_y_ballaeast_01","Ballas East Male"},
{"g_m_y_ballaorig_01","Ballas Original Male"},
{"g_m_y_ballasout_01","Ballas South Male"},
{"g_m_y_famca_01","Families CA Male"},
{"g_m_y_famdnf_01","Families DNF Male"},
{"g_m_y_famfor_01","Families FOR Male"},
{"g_m_y_korean_01","Korean Young Male"},
{"g_m_y_korean_02","Korean Young Male 2"},
{"g_m_y_korlieut_01","Korean Lieutenant"},
{"g_m_y_lost_01","The Lost MC Male"},
{"g_m_y_lost_02","The Lost MC Male 2"},
{"g_m_y_lost_03","The Lost MC Male 3"},
{"g_m_y_mexgang_01","Mexican Gang Member"},
{"g_m_y_mexgoon_01","Mexican Goon"},
{"g_m_y_mexgoon_02","Mexican Goon 2"},
{"g_m_y_mexgoon_03","Mexican Goon 3"},
{"g_m_y_mexgoon_03_p","Mexican Goon 3"},
{"g_m_y_pologoon_01_p","Polynesian Goon"},
{"g_m_y_pologoon_01","Polynesian Goon"},
{"g_m_y_pologoon_02_p","Polynesian Goon 2"},
{"g_m_y_pologoon_02","Polynesian Goon 2"},
{"g_m_y_salvaboss_01","Salvadoran Boss"},
{"g_m_y_salvagoon_01","Salvadoran Goon"},
{"g_m_y_salvagoon_02","Salvadoran Goon 2"},
{"g_m_y_salvagoon_03_p","Salvadoran Goon 3"},
{"g_m_y_salvagoon_03","Salvadoran Goon 3"},
{"g_m_y_strpunk_01","Street Punk"},
{"g_m_y_strpunk_02","Street Punk 2"},
{"hc_driver","Jewel Heist Driver"},
{"hc_gunman","Jewel Heist Gunman"},
{"hc_hacker","Jewel Heist Hacker"},
{"ig_abigail","Abigail Mathers"},
{"ig_agent","Agent"},
{"ig_amandatownley","Amanda De Santa"},
{"ig_andreas","Andreas Sanchez"},
{"ig_ashley","Ashley Butler"},
{"ig_avon","Avon Hertz"},
{"ig_ballasog","Ballas OG"},
{"ig_bankman","Bank Manager"},
{"ig_barry","Barry"},
{"ig_barry_p","Barry P"},
{"ig_benny","Benny"},
{"ig_bestmen","Best Man"},
{"ig_beverly","Beverly Felton"},
{"ig_beverly_p","Beverly Felton P"},
{"ig_brad","Brad"},
{"ig_bride","Bride"},
{"ig_car3guy1","Car 3 Guy 1"},
{"ig_car3guy2","Car 3 Guy 2"},
{"ig_casey","Casey"},
{"ig_chef2","Chef"},
{"ig_chef","Chef"},
{"ig_chengsr","Wei Cheng"},
{"ig_chrisformage","Cris Formage"},
{"ig_clay","Clay Simons (The Lost)"},
{"ig_claypain","Clay Jackson (The Pain Giver)"},
{"ig_cletus","Cletus"},
{"ig_dale","Dale"},
{"ig_davenorton","Dave Norton"},
{"ig_denise","Denise"},
{"ig_devin","Devin"},
{"ig_dix","Dix"},
{"ig_djblamadon","DJ Blam Adon"},
{"ig_djblamrupert","DJ Blam Rupert"},
{"ig_djblamryanh","DJ Blam Ryan H"},
{"ig_djblamryans","DJ Blam Ryan S"},
{"ig_djdixmanager","DJ Dix Manager"},
{"ig_djgeneric_01","DJ Generic"},
{"ig_djsolfotios","DJ Sol Fotios"},
{"ig_djsoljakob","DJ Sol Jakob"},
{"ig_djsolmanager","DJ Sol Manager"},
{"ig_djsolmike","DJ Sol Mike"},
{"ig_djsolrobt","DJ Sol Rob T"},
{"ig_djtalaurelia","DJ Tal Aurelia"},
{"ig_djtalignazio","DJ Tal Ignazio"},
{"ig_dom","Dom Beasley"},
{"ig_dreyfuss","Peter Dreyfuss"},
{"ig_drfriedlander","Dr. Friedlander"},
{"ig_englishdave","English Dave"},
{"ig_fabien","Fabien"},
{"ig_fbisuit_01","FIB Suit"},
{"ig_floyd","Floyd Hebert"},
{"ig_g","Gerald"},
{"ig_groom","Groom"},
{"ig_hao","Hao"},
{"ig_hunter","Hunter"},
{"ig_janet","Janet"},
{"ig_jay_norris","Jay Norris"},
{"ig_jewelass","Jeweller Assistant"},
{"ig_jimmyboston","Jimmy Boston"},
{"ig_jimmyboston_02","Jimmy Boston"},
{"ig_jimmydisanto","Jimmy De Santa"},
{"ig_joeminuteman","Minuteman Joe"},
{"ig_johnnyklebitz","Johnny Klebitz"},
{"ig_josef","Josef"},
{"ig_josh","Josh"},
{"ig_karen_daniels","Karen Daniels"},
{"ig_kerrymcintosh","Kerry McIntosh"},
{"ig_kerrymcintosh_02","Kerry McIntosh"},
{"ig_lacey_jones_02","Lacey Jones"},
{"ig_lamardavis","Lamar Davis"},
{"ig_lazlow","Lazlow"},
{"ig_lazlow_2","Lazlow"},
{"ig_lestercrest","Lester Crest"},
{"ig_lestercrest_2","Lester Crest (Doomsday Heist)"},
{"ig_lifeinvad_01","Life Invader"},
{"ig_lifeinvad_02","Life Invader 2"},
{"ig_magenta","Magenta"},
{"ig_malc","Malc"},
{"ig_manuel","Manuel"},
{"ig_marnie","Marnie Allen"},
{"ig_maryann","Mary-Ann Quinn"},
{"ig_maude","Maude"},
{"ig_michelle","Michelle"},
{"ig_milton","Milton McIlroy"},
{"ig_molly","Molly"},
{"ig_money","Money Man"},
{"ig_mp_agent14","Agent 14"},
{"ig_mrk","Ferdinand Kerimov (Mr. K)"},
{"ig_mrs_thornhill","Mrs. Thornhill"},
{"ig_mrsphillips","Mrs. Phillips"},
{"ig_natalia","Natalia"},
{"ig_nervousron","Nervous Ron"},
{"ig_nigel","Nigel"},
{"ig_old_man1a","Old Man 1"},
{"ig_old_man2","Old Man 2"},
{"ig_omega","Omega"},
{"ig_oneil","O'Neil Brothers"},
{"ig_orleans","Bigfoot"},
{"ig_ortega","Ortega"},
{"ig_paige","Paige Harris"},
{"ig_paper","United Paper Man"},
{"ig_patricia","Patricia"},
{"ig_popov","Dima Popov"},
{"ig_priest","Priest"},
{"ig_prolsec_02","Prologue Security 2"},
{"ig_ramp_gang","Families Gang Member?"},
{"ig_ramp_hic","Hick"},
{"ig_ramp_hipster","Hipster"},
{"ig_ramp_mex","Mexican"},
{"ig_rashcosvki","Maxim Rashkovsky"},
{"ig_roccopelosi","Rocco Pelosi"},
{"ig_russiandrunk","Russian Drunk"},
{"ig_screen_writer","Screenwriter"},
{"ig_siemonyetarian","Simeon Yetarian"},
{"ig_sol","Sol"},
{"ig_solomon","Solomon Richards"},
{"ig_stevehains","Steve Haines"},
{"ig_stretch","Stretch"},
{"ig_talcc","Talc"},
{"ig_talina","Talina"},
{"ig_talmm","Talm"},
{"ig_tanisha","Tanisha"},
{"ig_taocheng","Tao Cheng"},
{"ig_taostranslator","Tao's Translator"},
{"ig_taostranslator_p","Tao's Translator"},
{"ig_tenniscoach","Tennis Coach"},
{"ig_terry","Terry"},
{"ig_tomepsilon","Epsilon Tom"},
{"ig_tonya","Tonya"},
{"ig_tonyprince","Tony  Prince"},
{"ig_tracydisanto","Tracey De Santa"},
{"ig_trafficwarden","Traffic Warden"},
{"ig_tylerdix","Tyler Dixon"},
{"ig_tylerdix_02","Tyler Dixon"},
{"ig_vagspeak","Vagos Funeral Speaker"},
{"ig_wade","Wade"},
{"ig_zimbor","Zimbor"},
{"mp_f_boatstaff_01","Boat-Staff Female"},
{"mp_f_cardesign_01","Office Garage Mechanic"},
{"mp_f_chbar_01","Clubhouse Bar Female"},
{"mp_f_cocaine_01","Biker Cocaine Female"},
{"mp_f_counterfeit_01","Biker Counterfeit Female"},
{"mp_f_deadhooker","Dead Hooker"},
{"mp_f_execpa_01","Executive PA Female"},
{"mp_f_execpa_02","Executive PA Female 2"},
{"mp_f_forgery_01","Biker Forgery Female"},
{"mp_f_freemode_01","Freemode Female"},
{"mp_f_helistaff_01","Heli-Staff Female"},
{"mp_f_meth_01","Biker Meth Female"},
{"mp_f_misty_01","Misty"},
{"mp_f_stripperlite","Stripper Lite"},
{"mp_f_weed_01","Biker Weed Female"},
{"mp_g_m_pros_01","Pros"},
{"mp_headtargets","Head Targets"},
{"mp_m_avongoon","Avon Goon"},
{"mp_m_boatstaff_01","Boat-Staff Male"},
{"mp_m_bogdangoon","Bogdan Goon"},
{"mp_m_claude_01","Claude Speed"},
{"mp_m_cocaine_01","Biker Cocaine Male"},
{"mp_m_counterfeit_01","Biker Counterfeit Male"},
{"mp_m_exarmy_01","Ex-Army Male"},
{"mp_m_execpa_01","Executive PA Male"},
{"mp_m_famdd_01","Families DD Male"},
{"mp_m_fibsec_01","FIB Security"},
{"mp_m_forgery_01","Biker Forgery Male"},
{"mp_m_freemode_01","Freemode Male"},
{"mp_m_g_vagfun_01","Vagos Funeral"},
{"mp_m_marston_01","John Marston"},
{"mp_m_meth_01","Biker Meth Male"},
{"mp_m_niko_01","Niko Bellic"},
{"mp_m_securoguard_01","Securoserve Guard"},
{"mp_m_shopkeep_01","Shopkeeper"},
{"mp_m_waremech_01","Vehicle Warehouse Mechanic"},
{"mp_m_weapexp_01","Weapon Exp"},
{"mp_m_weapexp_01_p","Weapon Exp p"},
{"mp_m_weapwork_01","Weapon Work"},
{"mp_m_weapwork_01_p","Weapon Work p"},
{"mp_m_weed_01","Biker Weed Male"},
{"mp_s_m_armoured_01","Armoured Van Security Male"},
{"player_one","Franklin"},
{"player_two","Trevor"},
{"player_zero","Michael"},
{"s_f_m_fembarber","Barber Female"},
{"s_f_m_maid_01","Maid"},
{"s_f_m_shop_high","Sales Assistant (High-End)"},
{"s_f_m_sweatshop_01","Sweatshop Worker"},
{"s_f_y_airhostess_01","Air Hostess"},
{"s_f_y_bartender_01","Bartender"},
{"s_f_y_baywatch_01","Baywatch Female"},
{"s_f_y_clubbar_01","Club Bar"},
{"s_f_y_cop_01","Cop Female"},
{"s_f_y_factory_01","Factory Worker Female"},
{"s_f_y_hooker_01","Hooker"},
{"s_f_y_hooker_02","Hooker 2"},
{"s_f_y_hooker_03","Hooker 3"},
{"s_f_y_migrant_01","Migrant Female"},
{"s_f_y_movprem_01","Movie Premiere Female"},
{"s_f_y_ranger_01","Ranger Female"},
{"s_f_y_scrubs_01","Hospital Scrubs Female"},
{"s_f_y_sheriff_01","Sheriff Female"},
{"s_f_y_shop_low","Sales Assistant (Low-End)"},
{"s_f_y_shop_mid","Sales Assistant (Mid-Price)"},
{"s_f_y_stripper_01","Stripper"},
{"s_f_y_stripper_02","Stripper 2"},
{"s_f_y_stripperlite","Stripper Lite"},
{"s_f_y_sweatshop_01","Sweatshop Worker Young"},
{"s_m_m_ammucountry","Ammu-Nation Rural Clerk"},
{"s_m_m_armoured_01","Armoured Van Security"},
{"s_m_m_armoured_02","Armoured Van Security 2"},
{"s_m_m_autoshop_01","Autoshop Worker"},
{"s_m_m_autoshop_02","Autoshop Worker 2"},
{"s_m_m_bouncer_01","Bouncer"},
{"s_m_m_ccrew_01","Crew Member"},
{"s_m_m_chemsec_01","Chemical Plant Security"},
{"s_m_m_ciasec_01","IAA Security"},
{"s_m_m_cntrybar_01","Bartender (Rural)"},
{"s_m_m_dockwork_01","Dock Worker"},
{"s_m_m_doctor_01","Doctor"},
{"s_m_m_fiboffice_01","FIB Office Worker"},
{"s_m_m_fiboffice_02","FIB Office Worker 2"},
{"s_m_m_fibsec_01","FIB Security"},
{"s_m_m_gaffer_01","Gaffer"},
{"s_m_m_gardener_01","Gardener"},
{"s_m_m_gentransport","Transport Worker Male"},
{"s_m_m_hairdress_01","Hairdresser Male"},
{"s_m_m_highsec_01","High Security"},
{"s_m_m_highsec_02","High Security 2"},
{"s_m_m_janitor","Janitor"},
{"s_m_m_lathandy_01","Latino Handyman Male"},
{"s_m_m_lifeinvad_01","Life Invader Male"},
{"s_m_m_linecook","Line Cook"},
{"s_m_m_lsmetro_01","LS Metro Worker Male"},
{"s_m_m_mariachi_01","Mariachi"},
{"s_m_m_marine_01","Marine"},
{"s_m_m_marine_02","Marine 2"},
{"s_m_m_migrant_01","Migrant Male"},
{"s_m_m_movalien_01","Alien"},
{"s_m_m_movprem_01","Movie Premiere Male"},
{"s_m_m_movspace_01","Movie Astronaut"},
{"s_m_m_paramedic_01","Paramedic"},
{"s_m_m_pilot_01","Pilot"},
{"s_m_m_pilot_02","Pilot 2"},
{"s_m_m_postal_01","Postal Worker Male"},
{"s_m_m_postal_02","Postal Worker Male 2"},
{"s_m_m_prisguard_01","Prison Guard"},
{"s_m_m_scientist_01","Scientist"},
{"s_m_m_security_01","Security Guard"},
{"s_m_m_snowcop_01","Snow Cop Male"},
{"s_m_m_strperf_01","Street Performer"},
{"s_m_m_strpreach_01","Street Preacher"},
{"s_m_m_strvend_01","Street Vendor"},
{"s_m_m_trucker_01","Trucker Male"},
{"s_m_m_ups_01","UPS Driver"},
{"s_m_m_ups_02","UPS Driver 2"},
{"s_m_o_busker_01","Busker"},
{"s_m_y_airworker","Air Worker Male"},
{"s_m_y_ammucity_01","Ammu-Nation City Clerk"},
{"s_m_y_armymech_01","Army Mechanic"},
{"s_m_y_autopsy_01","Autopsy Tech"},
{"s_m_y_barman_01","Barman"},
{"s_m_y_baywatch_01","Baywatch Male"},
{"s_m_y_blackops_01","Black Ops Soldier"},
{"s_m_y_blackops_02","Black Ops Soldier 2"},
{"s_m_y_blackops_03","Black Ops Soldier 3"},
{"s_m_y_busboy_01","Busboy"},
{"s_m_y_chef_01","Chef"},
{"s_m_y_clown_01","Clown"},
{"s_m_y_clubbar_01","Club Bar"},
{"s_m_y_construct_01","construction Worker"},
{"s_m_y_construct_02","construction Worker 2"},
{"s_m_y_cop_01","Cop Male"},
{"s_m_y_dealer_01","Dealer"},
{"s_m_y_devinsec_01","Devin's Security"},
{"s_m_y_dockwork_01","Dock Worker"},
{"s_m_y_doorman_01","Doorman"},
{"s_m_y_dwservice_01","DW Airport Worker"},
{"s_m_y_dwservice_02","DW Airport Worker 2"},
{"s_m_y_factory_01","Factory Worker Male"},
{"s_m_y_fireman_01","Fireman Male"},
{"s_m_y_garbage","Garbage Worker"},
{"s_m_y_grip_01","Grip"},
{"s_m_y_hwaycop_01","Highway Cop"},
{"s_m_y_marine_01","Marine Young"},
{"s_m_y_marine_02","Marine Young 2"},
{"s_m_y_marine_03","Marine Young 3"},
{"s_m_y_mime","Mime Artist"},
{"s_m_y_pestcont_01","Pest Control"},
{"s_m_y_pilot_01","Pilot"},
{"s_m_y_prismuscl_01","Prisoner (Muscular)"},
{"s_m_y_prisoner_01","Prisoner"},
{"s_m_y_ranger_01","Ranger Male"},
{"s_m_y_robber_01","Robber"},
{"s_m_y_sheriff_01","Sheriff Male"},
{"s_m_y_shop_mask","Sales Assistant (Mask Stall)"},
{"s_m_y_strvend_01","Street Vendor Young"},
{"s_m_y_swat_01","SWAT"},
{"s_m_y_uscg_01","US Coastguard"},
{"s_m_y_valet_01","Valet"},
{"s_m_y_waiter_01","Waiter"},
{"s_m_y_waretech_01","Ware tech"},
{"s_m_y_winclean_01","Window Cleaner"},
{"s_m_y_xmech_01","Mechanic"},
{"s_m_y_xmech_02_mp","Mechanic 2"},
{"s_m_y_xmech_02","MC Clubhouse Mechanic"},
{"u_f_m_corpse_01","Corpse Female"},
{"u_f_m_drowned_01","Drowned"},
{"u_f_m_miranda","Miranda"},
{"u_f_m_miranda_02","Miranda"},
{"u_f_m_promourn_01","Prologue Mourner Female"},
{"u_f_o_moviestar","Movie Star Female"},
{"u_f_o_prolhost_01","Prologue Host Old Female"},
{"u_f_y_bikerchic","Biker Chic Female"},
{"u_f_y_comjane","Jane"},
{"u_f_y_corpse_01","Corpse Young Female"},
{"u_f_y_corpse_02","Corpse Young Female 2"},
{"u_f_y_danceburl_01","Dance Burl"},
{"u_f_y_dancelthr_01","Dance Leather"},
{"u_f_y_dancerave_01","Dance Rave"},
{"u_f_y_hotposh_01","Hot Posh Female"},
{"u_f_y_jewelass_01","Jeweller Assistant"},
{"u_f_y_mistress","Mistress"},
{"u_f_y_poppymich","Poppy Mitchell"},
{"u_f_y_poppymich_02","Poppy Mitchell"},
{"u_f_y_princess","Princess"},
{"u_f_y_spyactress","Spy Actress"},
{"u_m_m_aldinapoli","Al Di Napoli Male"},
{"u_m_m_bankman","Bank Manager Male"},
{"u_m_m_bikehire_01","Bike Hire Guy"},
{"u_m_m_doa_01","DOA Man"},
{"u_m_m_edtoh","Ed Toh"},
{"u_m_m_fibarchitect","FIB Architect"},
{"u_m_m_filmdirector","Movie Director"},
{"u_m_m_glenstank_01","Glen-Stank Male"},
{"u_m_m_griff_01","Griff"},
{"u_m_m_jesus_01","Jesus"},
{"u_m_m_jewelsec_01","Jeweller Security"},
{"u_m_m_jewelthief","Jewel Thief"},
{"u_m_m_markfost","Mark Fostenburg"},
{"u_m_m_partytarget","Party Target"},
{"u_m_m_prolsec_01","Prologue Security"},
{"u_m_m_promourn_01","Prologue Mourner Male"},
{"u_m_m_rivalpap","Rival Paparazzo"},
{"u_m_m_spyactor","Spy Actor"},
{"u_m_m_streetart_01","Street Art Male"},
{"u_m_m_willyfist","Love Fist Willy"},
{"u_m_o_filmnoir","Movie Corpse (Suited)"},
{"u_m_o_finguru_01","Financial Guru"},
{"u_m_o_taphillbilly","Jesco White (Tapdancing Hillbilly)"},
{"u_m_o_tramp_01","Tramp Old Male"},
{"u_m_y_abner","Abner"},
{"u_m_y_antonb","Anton Beaudelaire"},
{"u_m_y_babyd","Baby D"},
{"u_m_y_baygor","Kifflom Guy"},
{"u_m_y_burgerdrug_01","Burger Drug Worker"},
{"u_m_y_chip","Chip"},
{"u_m_y_corpse_01","Dead Courier"},
{"u_m_y_cyclist_01","Cyclist Male"},
{"u_m_y_danceburl_01","Dance Burl"},
{"u_m_y_dancelthr_01","Dance Leather"},
{"u_m_y_dancerave_01","Dance Rave"},
{"u_m_y_fibmugger_01","FIB Mugger"},
{"u_m_y_guido_01","Guido"},
{"u_m_y_gunvend_01","Gun Vendor"},
{"u_m_y_hippie_01","Hippie Male"},
{"u_m_y_imporage","Impotent Rage"},
{"u_m_y_juggernaut_01","Avon Juggernaut"},
{"u_m_y_justin","Justin"},
{"u_m_y_mani","Mani"},
{"u_m_y_militarybum","Ex-Mil Bum"},
{"u_m_y_paparazzi","Paparazzi Young Male"},
{"u_m_y_party_01","Partygoer"},
{"u_m_y_pogo_01","Pogo the Monkey"},
{"u_m_y_prisoner_01","Prisoner"},
{"u_m_y_proldriver_01","Prologue Driver"},
{"u_m_y_rsranger_01","Republican Space Ranger"},
{"u_m_y_sbike","Sports Biker"},
{"u_m_y_smugmech_01","Hangar Mechanic"},
{"u_m_y_staggrm_01","Stag Party Groom"},
{"u_m_y_tattoo_01","Tattoo Artist"},
{"u_m_y_zombie_01","Zombie"},
}

ped_models.rltshp_csa = {
[get_hash("COP")] = true,
[get_hash("SECURITY_GUARD")] = true,
[get_hash("PRIVATE_SECURITY")] = true,
[get_hash("ARMY")] = true}

ped_models.rltshp_mssn = {
[get_hash("HATES_PLAYER")] = true,
[get_hash("SPECIAL")] = true,
[get_hash("MISSION2")] = true,
[get_hash("MISSION3")] = true,
[get_hash("MISSION4")] = true,
[get_hash("MISSION5")] = true,
[get_hash("MISSION6")] = true,
[get_hash("MISSION7")] = true,
[get_hash("MISSION8")] = true,
[get_hash("AGGRESSIVE_INVESTIGATE")] = true,
[get_hash("GANG_1")] = true,
[get_hash("GANG_2")] = true,
[get_hash("GANG_9")] = true,
[get_hash("GANG_10")] = true,
[get_hash("AMBIENT_GANG_LOST")] = true,
[get_hash("AMBIENT_GANG_MEXICAN")] = true,
[get_hash("AMBIENT_GANG_FAMILY")] = true,
[get_hash("AMBIENT_GANG_BALLAS")] = true,
[get_hash("AMBIENT_GANG_MARABUNTE")] = true,
[get_hash("AMBIENT_GANG_CULT")] = true,
[get_hash("AMBIENT_GANG_SALVA")] = true,
[get_hash("AMBIENT_GANG_WEICHENG")] = true,
[get_hash("AMBIENT_GANG_HILLBILLY")] = true}

ped_models.rltshp_anml = {
[get_hash("HEN")] = true,
[get_hash("WILD_ANIMAL")] = true,
[get_hash("SHARK")] = true,
[get_hash("COUGAR")] = true,
[get_hash("CAT")] = true,
[get_hash("GUARD_DOG")] = true}

ped_models.rltshp_anml_hash = {
[get_hash("A_C_Westy")] = true, -- Hash: -138462701
[get_hash("A_C_TigerShark")] = true, -- Hash: 113504370
[get_hash("A_C_Shepherd")] = true, -- Hash: 1126154828
[get_hash("A_C_Rottweiler")] = true, -- Hash: -1788665315
[get_hash("A_C_Rat")] = true, -- Hash: -1011537562
[get_hash("A_C_Rhesus")] = true, -- Hash: -1026527405
[get_hash("A_C_Retriever")] = true, -- Hash: 882848737
[get_hash("A_C_Rabbit")] = true, -- Hash: -541762431
[get_hash("A_C_Pug")] = true, -- Hash: 1832265812
[get_hash("A_C_Poodle")] = true, -- Hash: 1125994524
[get_hash("A_C_Pigeon")] = true, -- Hash: 111281960
[get_hash("A_C_Pig")] = true, -- Hash: -1323586730
[get_hash("A_C_OrleansCutscene")] = true, -- Hash: -1389097126
[get_hash("A_C_Orleans")] = true, -- Hash: 1641334641
[get_hash("A_C_MountainLion")] = true, -- Hash: 307287994
[get_hash("A_C_KillerWhale")] = true, -- Hash: -1920284487
[get_hash("A_C_Husky")] = true, -- Hash: 1318032802
[get_hash("A_C_Humpback")] = true, -- Hash: 1193010354
[get_hash("A_C_Hen")] = true, -- Hash: 1794449327
[get_hash("A_C_HammerShark")] = true, -- Hash: 1015224100
[get_hash("A_C_Fish")] = true, -- Hash: 802685111
[get_hash("A_C_Dolphin")] = true, -- Hash: -1950698411
[get_hash("A_C_Deer")] = true, -- Hash: -664053099
[get_hash("A_C_Crow")] = true, -- Hash: 402729631
[get_hash("A_C_Coyote")] = true, -- Hash: 1682622302
[get_hash("A_C_Cow")] = true, -- Hash: -50684386
[get_hash("A_C_Cormorant")] = true, -- Hash: 1457690978
[get_hash("A_C_Chop")] = true, -- Hash: 351016938
[get_hash("A_C_Chimp")] = true, -- Hash: -1469565163
[get_hash("A_C_ChickenHawk")] = true, -- Hash: -1430839454
[get_hash("A_C_Cat")] = true, -- Hash: 1462895032
[get_hash("A_C_Boar")] = true, -- Hash: -832573324
}

ped_models.change_weap_list = {
get_hash("weapon_unarmed"),         --fists
get_hash("weapon_knuckle"),         -- Kuckle Dusters = 0xD8DF3C3C
get_hash("weapon_knife"),           -- knife = 0x99B507EA
get_hash("weapon_battleaxe"),       -- battle axe 3441901897
get_hash("weapon_stungun"),         -- stungun = 0x3656C8C1
get_hash("weapon_revolver_mk2"),    -- heavy revolver mk2
get_hash("weapon_machinepistol"),   -- machinepistol = 0xDB1AA450
get_hash("weapon_raypistol"),       -- atomizer 0xAF3696A1
get_hash("weapon_raycarbine"),      -- Unholy Hellbringer 0x476BF155
get_hash("weapon_combatmg_mk2"),    -- combatmg_mk2 = 0xDBBD7280
get_hash("weapon_heavysniper_mk2"), -- Heavy Sniper Mk II", 177293209
get_hash("weapon_rayminigun"),      -- Widowmaker, 0xB62D1F67
get_hash("weapon_emplauncher"),     -- EMP Gun", 0xDB26713A
get_hash("weapon_firework"),        -- Firework launcher", 0x7F7497E5
get_hash("weapon_rpg"),             -- Standard_RPG = 2982836145
get_hash("weapon_railgun"),         -- railgun = 0x6D544C99

}

ped_models.change_weap_ammo = {
1,--fists
1,-- Kuckle Dusters = 0xD8DF3C3C
1,-- knife = 0x99B507EA
1,-- battle axe 3441901897
1,-- stungun = 0x3656C8C1
6000,-- heavy revolver mk2
6000,-- machinepistol = 0xDB1AA450
1,-- atomizer 0xAF3696A1
1,-- Unholy Hellbringer 0x476BF155
6000,-- combatmg_mk2 = 0xDBBD7280
30,-- Heavy Sniper Mk II", 177293209
6000,-- Widowmaker, 0xB62D1F67
20,-- EMP Gun", 0xDB26713A
20,-- Firework launcher", 0x7F7497E5
20,-- Standard_RPG = 2982836145
20,-- railgun = 0x6D544C99
}

ped_models.hash_is_name={}
for i=1,#ped_models.peds do
	ped_models.hash_is_name[get_hash(ped_models.peds[i][1])]=ped_models.peds[i][2]
end
return ped_models


-- local list = {
-- ["CTaskHandsUp = 0,"] =			2,
-- ["CTaskClimbLadder = 1,"] =			2, 
-- ["CTaskExitVehicle = 2,"] =			2,
-- ["CTaskCombatRoll = 3,"] =			2,
-- ["CTaskAimGunOnFoot = 4,"] =			2,
-- ["CTaskMovePlayer = 5,"] =			2,
-- ["CTaskPlayerOnFoot = 6,"] =			2,
-- ["CTaskWeapon = 8,"] =			4,
-- ["CTaskPlayerWeapon = 9,"] =			5,
-- ["CTaskPlayerIdles = 10,"] =			10,
-- ["CTaskAimGun = 12,"] =			12,
-- ["CTaskComplex = 12,"] =			12,
-- ["CTaskFSMClone = 12,"] =			12,
-- ["CTaskMotionBase = 12,"] =			12,
-- ["CTaskMove = 12,"] =			12,
-- ["CTaskMoveBase = 12,"] =			12,
-- ["CTaskNMBehaviour = 12,"] =			12,
-- ["CTaskNavBase = 12,"] =			12,
-- ["CTaskScenario = 12,"] =			12,
-- ["CTaskSearchBase = 12,"] =			12,
-- ["CTaskSearchInVehicleBase = 12,"] =			12,
-- ["CTaskShockingEvent = 12,"] =			12,
-- ["CTaskTrainBase = 12,"] =			12,
-- ["CTaskVehicleFSM = 12,"] =			12,
-- ["CTaskVehicleGoTo = 12,"] =			12,
-- ["CTaskVehicleMissionBase = 12,"] =			12,
-- ["CTaskVehicleTempAction = 12,"] =			12,
-- ["CTaskPause = 14,"] =			14,
-- ["CTaskDoNothing = 15,"] =			15,
-- ["CTaskGetUp = 16,"] =			16,
-- ["CTaskGetUpAndStandStill = 17,"] =			17,
-- ["CTaskFallOver = 18,"] =			18,
-- ["CTaskFallAndGetUp = 19,"] =			19,
-- ["CTaskCrawl = 20,"] =			20,
-- ["CTaskComplexOnFire = 25,"] =			25,
-- ["CTaskDamageElectric = 26,"] =			26,
-- ["CTaskTriggerLookAt = 28,"] =			28,
-- ["CTaskClearLookAt = 29,"] =			29,
-- ["CTaskSetCharDecisionMaker = 30,"] =			30,
-- ["CTaskSetPedDefensiveArea = 31,"] =			31,
-- ["CTaskUseSequence = 32,"] =			32,
-- ["CTaskMoveStandStill = 34,"] =			34,
-- ["CTaskComplexControlMovement = 35,"] =			35,
-- ["CTaskMoveSequence = 36,"] =			36,
-- ["CTaskAmbientClips = 38,"] =			38,
-- ["CTaskMoveInAir = 39,"] =			39,
-- ["CTaskNetworkClone = 40,"] =			40,
-- ["CTaskUseClimbOnRoute = 41,"] =			41, 
-- ["CTaskUseDropDownOnRoute = 42,"] =			42,
-- ["CTaskUseLadderOnRoute = 43,"] =			43,
-- ["CTaskSetBlockingOfNonTemporaryEvents = 44,"] =			44,
-- ["CTaskForceMotionState = 45,"] =			45,
-- ["CTaskSlopeScramble = 46,"] =			46,
-- ["CTaskGoToAndClimbLadder = 47,"] =			47,
-- ["CTaskClimbLadderFully = 48,"] =			48,
-- ["CTaskRappel = 49,"] =			49,
-- ["CTaskVault = 50,"] =			50, 
-- ["CTaskDropDown = 51,"] =			51,
-- ["CTaskAffectSecondaryBehaviour = 52,"] =			52,
-- ["CTaskAmbientLookAtEvent = 53,"] =			53,
-- ["CTaskOpenDoor = 54,"] =			54,
-- ["CTaskShovePed = 55,"] =			55,
-- ["CTaskSwapWeapon = 56,"] =			56,
-- ["CTaskGeneralSweep = 57,"] =			57,
-- ["CTaskPolice = 58,"] =			58,
-- ["CTaskPoliceOrderResponse = 59,"] =			59,
-- ["CTaskPursueCriminal = 60,"] =			60,
-- ["CTaskArrestPed = 62,"] =			62,
-- ["CTaskArrestPed2 = 63,"] =			63,
-- ["CTaskBusted = 64,"] =			64,
-- ["CTaskFirePatrol = 65,"] =			65,
-- ["CTaskHeliOrderResponse = 66,"] =			66,
-- ["CTaskHeliPassengerRappel = 67,"] =			67,
-- ["CTaskAmbulancePatrol = 68,"] =			68,
-- ["CTaskPoliceWantedResponse = 69,"] =			69,
-- ["CTaskSwat = 70,"] =			70,
-- ["CTaskSwatWantedResponse = 72,"] =			72,
-- ["CTaskSwatOrderResponse = 73,"] =			73,
-- ["CTaskSwatGoToStagingArea = 74,"] =			74,
-- ["CTaskSwatFollowInLine = 75,"] =			75,
-- ["CTaskWitness = 76,"] =			76,
-- ["CTaskGangPatrol = 77,"] =			77,
-- ["CTaskArmy = 78,"] =			78,
-- ["CTaskShockingEventWatch = 80,"] =			80,
-- ["CTaskShockingEventGoto = 82,"] =			82,
-- ["CTaskShockingEventHurryAway = 83,"] =			83,
-- ["CTaskShockingEventReactToAircraft = 84,"] =			84,
-- ["CTaskShockingEventReact = 85,"] =			85,
-- ["CTaskShockingEventBackAway = 86,"] =			86,
-- ["CTaskShockingPoliceInvestigate = 87,"] =			87,
-- ["CTaskShockingEventStopAndStare = 88,"] =			88,
-- ["CTaskShockingNiceCarPicture = 89,"] =			89,
-- ["CTaskShockingEventThreatResponse = 90,"] =			90,
-- ["CTaskTakeOffHelmet = 92,"] =			92,
-- ["CTaskCarReactToVehicleCollision = 93,"] =			93,
-- ["CTaskCarReactToVehicleCollisionGetOut = 95,"] =			95,
-- ["CTaskDyingDead = 97,"] =			97,
-- ["CTaskWanderingScenario = 100,"] =			100,
-- ["CTaskWanderingInRadiusScenario = 101,"] =			101,
-- ["CTaskMoveBetweenPointsScenario = 103,"] =			103,
-- ["CTaskChatScenario = 104,"] =			104,
-- ["CTaskCowerScenario = 106,"] =			106,
-- ["CTaskDeadBodyScenario = 107,"] =			107,
-- ["CTaskSayAudio = 114,"] =			114,
-- ["CTaskWaitForSteppingOut = 116,"] =			116,
-- ["CTaskCoupleScenario = 117,"] =			117,
-- ["CTaskUseScenario = 118,"] =			118,
-- ["CTaskUseVehicleScenario = 119,"] =			119,
-- ["CTaskUnalerted = 120,"] =			120,
-- ["CTaskStealVehicle = 121,"] =			121,
-- ["CTaskReactToPursuit = 122,"] =			122,
-- ["CTaskHitWall = 125,"] =			125,
-- ["CTaskCower = 126,"] =			126,
-- ["CTaskCrouch = 127,"] =			127,
-- ["CTaskMelee = 128,"] =			128,
-- ["CTaskMoveMeleeMovement = 129,"] =			129,
-- ["CTaskMeleeActionResult = 130,"] =			130,
-- ["CTaskMeleeUpperbodyAnims = 131,"] =			131,
-- ["CTaskMoVEScripted = 133,"] =			133,
-- ["CTaskScriptedAnimation = 134,"] =			134,
-- ["CTaskSynchronizedScene = 135,"] =			135,
-- ["CTaskComplexEvasiveStep = 137,"] =			137,
-- ["CTaskWalkRoundCarWhileWandering = 138,"] =			138,
-- ["CTaskComplexStuckInAir = 140,"] =			140,
-- ["CTaskWalkRoundEntity = 141,"] =			141,
-- ["CTaskMoveWalkRoundVehicle = 142,"] =			142,
-- ["CTaskReactToGunAimedAt = 144,"] =			144,
-- ["CTaskDuckAndCover = 146,"] =			146,
-- ["CTaskAggressiveRubberneck = 147,"] =			147,
-- ["CTaskInVehicleBasic = 150,"] =			150,
-- ["CTaskCarDriveWander = 151,"] =			151,
-- ["CTaskLeaveAnyCar = 152,"] =			152,
-- ["CTaskComplexGetOffBoat = 153,"] =			153,
-- ["CTaskCarSetTempAction = 155,"] =			155,
-- ["CTaskBringVehicleToHalt = 156,"] =			156,
-- ["CTaskCarDrive = 157,"] =			157,
-- ["CTaskPlayerDrive = 159,"] =			159,
-- ["CTaskEnterVehicle = 160,"] =			160,
-- ["CTaskEnterVehicleAlign = 161,"] =			161,
-- ["CTaskOpenVehicleDoorFromOutside = 162,"] =			162,
-- ["CTaskEnterVehicleSeat = 163,"] =			163,
-- ["CTaskCloseVehicleDoorFromInside = 164,"] =			164,
-- ["CTaskInVehicleSeatShuffle = 165,"] =			165,
-- ["CTaskExitVehicleSeat = 167,"] =			167,
-- ["CTaskCloseVehicleDoorFromOutside = 168,"] =			168,
-- ["CTaskControlVehicle = 169,"] =			169,
-- ["CTaskMotionInAutomobile = 170,"] =			170,
-- ["CTaskMotionOnBicycle = 171,"] =			171,
-- ["CTaskMotionOnBicycleController = 172,"] =			172,
-- ["CTaskMotionInVehicle = 173,"] =			173,
-- ["CTaskMotionInTurret = 174,"] =			174,
-- ["CTaskReactToBeingJacked = 175,"] =			175,
-- ["CTaskReactToBeingAskedToLeaveVehicle = 176,"] =			176,
-- ["CTaskTryToGrabVehicleDoor = 177,"] =			177,
-- ["CTaskGetOnTrain = 178,"] =			178,
-- ["CTaskGetOffTrain = 179,"] =			179,
-- ["CTaskRideTrain = 180,"] =			180,
-- ["CTaskMountThrowProjectile = 190,"] =			190,
-- ["CTaskGoToCarDoorAndStandStill = 195,"] =			195,
-- ["CTaskMoveGoToVehicleDoor = 196,"] =			196,
-- ["CTaskSetPedInVehicle = 197,"] =			197,
-- ["CTaskSetPedOutOfVehicle = 198,"] =			198,
-- ["CTaskVehicleMountedWeapon = 199,"] =			199,
-- ["CTaskVehicleGun = 200,"] =			200,
-- ["CTaskVehicleProjectile = 201,"] =			201,
-- ["CTaskSmashCarWindow = 204,"] =			204,
-- ["CTaskMoveGoToPoint = 205,"] =			205,
-- ["CTaskMoveAchieveHeading = 206,"] =			206,
-- ["CTaskMoveFaceTarget = 207,"] =			207,
-- ["CTaskComplexGoToPointAndStandStillTimed = 208,"] =			208,
-- ["CTaskMoveGoToPointAndStandStill = 208,"] =			208,
-- ["CTaskMoveFollowPointRoute = 209,"] =			209,
-- ["CTaskMoveSeekEntity_CEntitySeekPosCalculatorStandard = 210,"] =			210,
-- ["CTaskMoveSeekEntity_CEntitySeekPosCalculatorLastNavMeshIntersection = 211,"] =			211,
-- ["CTaskMoveSeekEntity_CEntitySeekPosCalculatorLastNavMeshIntersection2 = 212,"] =			212,
-- ["CTaskMoveSeekEntity_CEntitySeekPosCalculatorXYOffsetFixed = 213,"] =			213,
-- ["CTaskMoveSeekEntity_CEntitySeekPosCalculatorXYOffsetFixed2 = 214,"] =			214,
-- ["CTaskExhaustedFlee = 215,"] =			215,
-- ["CTaskGrowlAndFlee = 216,"] =			216,
-- ["CTaskScenarioFlee = 217,"] =			217,
-- ["CTaskSmartFlee = 218,"] =			218,
-- ["CTaskFlyAway = 219,"] =			219,
-- ["CTaskWalkAway = 220,"] =			220,
-- ["CTaskWander = 221,"] =			221,
-- ["CTaskWanderInArea = 222,"] =			222,
-- ["CTaskFollowLeaderInFormation = 223,"] =			223,
-- ["CTaskGoToPointAnyMeans = 224,"] =			224,
-- ["CTaskTurnToFaceEntityOrCoord = 225,"] =			225,
-- ["CTaskFollowLeaderAnyMeans = 226,"] =			226,
-- ["CTaskFlyToPoint = 228,"] =			228,
-- ["CTaskFlyingWander = 229,"] =			229,
-- ["CTaskGoToPointAiming = 230,"] =			230,
-- ["CTaskGoToScenario = 231,"] =			231,
-- ["CTaskSeekEntityAiming = 233,"] =			233,
-- ["CTaskSlideToCoord = 234,"] =			234,
-- ["CTaskSwimmingWander = 235,"] =			235,
-- ["CTaskMoveTrackingEntity = 237,"] =			237,
-- ["CTaskMoveFollowNavMesh = 238,"] =			238,
-- ["CTaskMoveGoToPointOnRoute = 239,"] =			239,
-- ["CTaskEscapeBlast = 240,"] =			240,
-- ["CTaskMoveWander = 241,"] =			241,
-- ["CTaskMoveBeInFormation = 242,"] =			242,
-- ["CTaskMoveCrowdAroundLocation = 243,"] =			243,
-- ["CTaskMoveCrossRoadAtTrafficLights = 244,"] =			244,
-- ["CTaskMoveWaitForTraffic = 245,"] =			245,
-- ["CTaskMoveGoToPointStandStillAchieveHeading = 246,"] =			246,
-- ["CTaskMoveGetOntoMainNavMesh = 251,"] =			251,
-- ["CTaskMoveSlideToCoord = 252,"] =			252,
-- ["CTaskMoveGoToPointRelativeToEntityAndStandStill = 253,"] =			253,
-- ["CTaskHelicopterStrafe = 254,"] =			254,
-- ["CTaskGetOutOfWater = 256,"] =			256,
-- ["CTaskMoveFollowEntityOffset = 259,"] =			259,
-- ["CTaskFollowWaypointRecording = 261,"] =			261,
-- ["CTaskMotionPed = 264,"] =			264,
-- ["CTaskMotionPedLowLod = 265,"] =			265,
-- ["CTaskHumanLocomotion = 268,"] =			268,
-- ["CTaskMotionBasicLocomotionLowLod = 269,"] =			269,
-- ["CTaskMotionStrafing = 270,"] =			270,
-- ["CTaskMotionTennis = 271,"] =			271,
-- ["CTaskMotionAiming = 272,"] =			272,
-- ["CTaskBirdLocomotion = 273,"] =			273,
-- ["CTaskFlightlessBirdLocomotion = 274,"] =			274,
-- ["CTaskFishLocomotion = 278,"] =			278,
-- ["CTaskQuadLocomotion = 279,"] =			279,
-- ["CTaskMotionDiving = 280,"] =			280,
-- ["CTaskMotionSwimming = 281,"] =			281,
-- ["CTaskMotionParachuting = 282,"] =			282,
-- ["CTaskMotionDrunk = 283,"] =			283,
-- ["CTaskRepositionMove = 284,"] =			284,
-- ["CTaskMotionAimingTransition = 285,"] =			285,
-- ["CTaskThrowProjectile = 286,"] =			286,
-- ["CTaskCover = 287,"] =			287,
-- ["CTaskMotionInCover = 288,"] =			288,
-- ["CTaskAimAndThrowProjectile = 289,"] =			289,
-- ["CTaskGun = 290,"] =			290,
-- ["CTaskAimFromGround = 291,"] =			291,
-- ["CTaskAimGunVehicleDriveBy = 295,"] =			295,
-- ["CTaskAimGunScripted = 296,"] =			296,
-- ["CTaskReloadGun = 298,"] =			298,
-- ["CTaskWeaponBlocked = 299,"] =			299,
-- ["CTaskEnterCover = 300,"] =			300,
-- ["CTaskExitCover = 301,"] =			301,
-- ["CTaskAimGunFromCoverIntro = 302,"] =			302,
-- ["CTaskAimGunFromCoverOutro = 303,"] =			303,
-- ["CTaskAimGunBlindFire = 304,"] =			304,
-- ["CTaskCombatClosestTargetInArea = 307,"] =			307,
-- ["CTaskCombatAdditionalTask = 308,"] =			308,
-- ["CTaskInCover = 309,"] =			309,
-- ["CTaskAimSweep = 313,"] =			313,
-- ["CTaskSharkCircle = 319,"] =			319,
-- ["CTaskSharkAttack = 320,"] =			320,
-- ["CTaskAgitated = 321,"] =			321,
-- ["CTaskAgitatedAction = 322,"] =			322,
-- ["CTaskConfront = 323,"] =			323,
-- ["CTaskIntimidate = 324,"] =			324,
-- ["CTaskShove = 325,"] =			325,
-- ["CTaskShoved = 326,"] =			326,
-- ["CTaskCrouchToggle = 328,"] =			328,
-- ["CTaskRevive = 329,"] =			329,
-- ["CTaskParachute = 335,"] =			335,
-- ["CTaskParachuteObject = 336,"] =			336,
-- ["CTaskTakeOffPedVariation = 337,"] =			337,
-- ["CTaskCombatSeekCover = 340,"] =			340,
-- ["CTaskCombatFlank = 342,"] =			342,
-- ["CTaskCombat = 343,"] =			343,
-- ["CTaskCombatMounted = 344,"] =			344,
-- ["CTaskMoveCircle = 345,"] =			345,
-- ["CTaskMoveCombatMounted = 346,"] =			346,
-- ["CTaskSearch = 347,"] =			347,
-- ["CTaskSearchOnFoot = 348,"] =			348,
-- ["CTaskSearchInAutomobile = 349,"] =			349,
-- ["CTaskSearchInBoat = 350,"] =			350,
-- ["CTaskSearchInHeli = 351,"] =			351,
-- ["CTaskThreatResponse = 352,"] =			352,
-- ["CTaskInvestigate = 353,"] =			353,
-- ["CTaskStandGuardFSM = 354,"] =			354,
-- ["CTaskPatrol = 355,"] =			355,
-- ["CTaskShootAtTarget = 356,"] =			356,
-- ["CTaskSetAndGuardArea = 357,"] =			357,
-- ["CTaskStandGuard = 358,"] =			358,
-- ["CTaskSeparate = 359,"] =			359,
-- ["CTaskStayInCover = 360,"] =			360,
-- ["CTaskVehicleCombat = 361,"] =			361,
-- ["CTaskVehiclePersuit = 362,"] =			362,
-- ["CTaskVehicleChase = 363,"] =			363,
-- ["CTaskDraggingToSafety = 364,"] =			364,
-- ["CTaskDraggedToSafety = 365,"] =			365,
-- ["CTaskVariedAimPose = 366,"] =			366,
-- ["CTaskMoveWithinAttackWindow = 367,"] =			367,
-- ["CTaskMoveWithinDefensiveArea = 368,"] =			368,
-- ["CTaskShootOutTire = 369,"] =			369,
-- ["CTaskShellShocked = 370,"] =			370,
-- ["CTaskBoatChase = 371,"] =			371,
-- ["CTaskBoatCombat = 372,"] =			372,
-- ["CTaskBoatStrafe = 373,"] =			373,
-- ["CTaskHeliChase = 374,"] =			374,
-- ["CTaskHeliCombat = 375,"] =			375,
-- ["CTaskSubmarineCombat = 376,"] =			376,
-- ["CTaskSubmarineChase = 377,"] =			377,
-- ["CTaskPlaneChase = 378,"] =			378,
-- ["CTaskTargetUnreachable = 379,"] =			379,
-- ["CTaskTargetUnreachableInInterior = 380,"] =			380,
-- ["CTaskTargetUnreachableInExterior = 381,"] =			381,
-- ["CTaskStealthKill = 382,"] =			382,
-- ["CTaskWrithe = 383,"] =			383,
-- ["CTaskAdvance = 384,"] =			384,
-- ["CTaskCharge = 385,"] =			385,
-- ["CTaskMoveToTacticalPoint = 386,"] =			386,
-- ["CTaskToHurtTransit = 387,"] =			387,
-- ["CTaskAnimatedHitByExplosion = 388,"] =			388,
-- ["CTaskNMRelax = 389,"] =			389,
-- ["CTaskNMPose = 391,"] =			391,
-- ["CTaskNMBrace = 392,"] =			392,
-- ["CTaskNMBuoyancy = 393,"] =			393,
-- ["CTaskNMInjuredOnGround = 394,"] =			394,
-- ["CTaskNMShot = 395,"] =			395,
-- ["CTaskNMHighFall = 396,"] =			396,
-- ["CTaskNMBalance = 397,"] =			397,
-- ["CTaskNMElectrocute = 398,"] =			398,
-- ["CTaskNMPrototype = 399,"] =			399,
-- ["CTaskNMExplosion = 400,"] =			400,
-- ["CTaskNMOnFire = 401,"] =			401,
-- ["CTaskNMScriptControl = 402,"] =			402,
-- ["CTaskNMJumpRollFromRoadVehicle = 403,"] =			403,
-- ["CTaskNMFlinch = 404,"] =			404,
-- ["CTaskNMSit = 405,"] =			405,
-- ["CTaskNMFallDown = 406,"] =			406,
-- ["CTaskBlendFromNM = 407,"] =			407,
-- ["CTaskNMControl = 408,"] =			408,
-- ["CTaskNMDangle = 409,"] =			409,
-- ["CTaskNMGenericAttach = 412,"] =			412,
-- ["CTaskNMDraggingToSafety = 414,"] =			414,
-- ["CTaskNMThroughWindscreen = 415,"] =			415,
-- ["CTaskNMRiverRapids = 416,"] =			416,
-- ["CTaskNMSimple = 417,"] =			417,
-- ["CTaskRageRagdoll = 418,"] =			418,
-- ["CTaskJumpVault = 421,"] =			421, 
-- ["CTaskJump = 422,"] =			422,
-- ["CTaskFall = 423,"] =			423,
-- ["CTaskReactAimWeapon = 425,"] =			425,
-- ["CTaskChat = 426,"] =			426,
-- ["CTaskMobilePhone = 427,"] =			427,
-- ["CTaskReactToDeadPed = 428,"] =			428,
-- ["CTaskSearchForUnknownThreat = 430,"] =			430,
-- ["CTaskBomb = 432,"] =			432,
-- ["CTaskDetonator = 433,"] =			433,
-- ["CTaskAnimatedAttach = 435,"] =			435,
-- ["CTaskCutScene = 441,"] =			441,
-- ["CTaskReactToExplosion = 442,"] =			442,
-- ["CTaskReactToImminentExplosion = 443,"] =			443,
-- ["CTaskDiveToGround = 444,"] =			444,
-- ["CTaskReactAndFlee = 445,"] =			445,
-- ["CTaskSidestep = 446,"] =			446,
-- ["CTaskCallPolice = 447,"] =			447,
-- ["CTaskReactInDirection = 448,"] =			448,
-- ["CTaskReactToBuddyShot = 449,"] =			449,
-- ["CTaskVehicleGoToAutomobileNew = 454,"] =			454,
-- ["CTaskVehicleGoToPlane = 455,"] =			455,
-- ["CTaskVehicleGoToHelicopter = 456,"] =			456,
-- ["CTaskVehicleGoToSubmarine = 457,"] =			457,
-- ["CTaskVehicleGoToBoat = 458,"] =			458,
-- ["CTaskVehicleGoToPointAutomobile = 459,"] =			459,
-- ["CTaskVehicleGoToPointWithAvoidanceAutomobile = 460,"] =			460,
-- ["CTaskVehiclePursue = 461,"] =			461,
-- ["CTaskVehicleRam = 462,"] =			462,
-- ["CTaskVehicleSpinOut = 463,"] =			463,
-- ["CTaskVehicleApproach = 464,"] =			464,
-- ["CTaskVehicleThreePointTurn = 465,"] =			465,
-- ["CTaskVehicleDeadDriver = 466,"] =			466,
-- ["CTaskVehicleCruiseNew = 467,"] =			467,
-- ["CTaskVehicleCruiseBoat = 468,"] =			468,
-- ["CTaskVehicleStop = 469,"] =			469,
-- ["CTaskVehiclePullOver = 470,"] =			470,
-- ["CTaskVehiclePassengerExit = 471,"] =			471,
-- ["CTaskVehicleFlee = 472,"] =			472,
-- ["CTaskVehicleFleeAirborne = 473,"] =			473,
-- ["CTaskVehicleFleeBoat = 474,"] =			474,
-- ["CTaskVehicleFollowRecording = 475,"] =			475,
-- ["CTaskVehicleFollow = 476,"] =			476,
-- ["CTaskVehicleBlock = 477,"] =			477,
-- ["CTaskVehicleBlockCruiseInFront = 478,"] =			478,
-- ["CTaskVehicleBlockBrakeInFront = 479,"] =			479,
-- ["CTaskVehicleBlockBackAndForth = 478,"] =			478,
-- ["CTaskVehicleCrash = 481,"] =			481,
-- ["CTaskVehicleLand = 482,"] =			482,
-- ["CTaskVehicleLandPlane = 483,"] =			483,
-- ["CTaskVehicleHover = 484,"] =			484,
-- ["CTaskVehicleAttack = 485,"] =			485,
-- ["CTaskVehicleAttackTank = 486,"] =			486,
-- ["CTaskVehicleCircle = 487,"] =			487,
-- ["CTaskVehiclePoliceBehaviour = 488,"] =			488,
-- ["CTaskVehiclePoliceBehaviourHelicopter = 489,"] =			489,
-- ["CTaskVehiclePoliceBehaviourBoat = 490,"] =			490,
-- ["CTaskVehicleEscort = 491,"] =			491,
-- ["CTaskVehicleHeliProtect = 492,"] =			492,
-- ["CTaskVehiclePlayerDriveAutomobile = 494,"] =			494,
-- ["CTaskVehiclePlayerDriveBike = 495,"] =			495,
-- ["CTaskVehiclePlayerDriveBoat = 496,"] =			496,
-- ["CTaskVehiclePlayerDriveSubmarine = 497,"] =			497,
-- ["CTaskVehiclePlayerDriveSubmarineCar = 498,"] =			498,
-- ["CTaskVehiclePlayerDriveAmphibiousAutomobile = 499,"] =			499,
-- ["CTaskVehiclePlayerDrivePlane = 500,"] =			500,
-- ["CTaskVehiclePlayerDriveHeli = 501,"] =			501,
-- ["CTaskVehiclePlayerDriveAutogyro = 502,"] =			502,
-- ["CTaskVehiclePlayerDriveDiggerArm = 503,"] =			503,
-- ["CTaskVehiclePlayerDriveTrain = 504,"] =			504,
-- ["CTaskVehiclePlaneChase = 505,"] =			505,
-- ["CTaskVehicleNoDriver = 506,"] =			506,
-- ["CTaskVehicleAnimation = 507,"] =			507,
-- ["CTaskVehicleConvertibleRoof = 508,"] =			508,
-- ["CTaskVehicleParkNew = 509,"] =			509,
-- ["CTaskVehicleFollowWaypointRecording = 510,"] =			510,
-- ["CTaskVehicleGoToNavmesh = 511,"] =			511,
-- ["CTaskVehicleReactToCopSiren = 512,"] =			512,
-- ["CTaskVehicleGotoLongRange = 513,"] =			513,
-- ["CTaskVehicleWait = 514,"] =			514,
-- ["CTaskVehicleReverse = 515,"] =			515,
-- ["CTaskVehicleBrake = 516,"] =			516,
-- ["CTaskVehicleHandBrake = 517,"] =			517,
-- ["CTaskVehicleTurn = 518,"] =			518,
-- ["CTaskVehicleGoForward = 519,"] =			519,
-- ["CTaskVehicleSwerve = 520,"] =			520,
-- ["CTaskVehicleFlyDirection = 521,"] =			521,
-- ["CTaskVehicleHeadonCollision = 522,"] =			522,
-- ["CTaskVehicleBoostUseSteeringAngle = 523,"] =			523,
-- ["CTaskVehicleShotTire = 524,"] =			524,
-- ["CTaskVehicleBurnout = 525,"] =			525,
-- ["CTaskVehicleRevEngine = 526,"] =			526,
-- ["CTaskVehicleSurfaceInSubmarine = 527,"] =			527,
-- ["CTaskVehiclePullAlongside = 528,"] =			528,
-- ["CTaskVehicleTransformToSubmarine = 529,"] =			529,
-- ["CTaskAnimatedFallback = 530"] =			 530
-- }